name: PR tests

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
              python-version: [3.8, 3.9, 3.10, 3.11]
              
        steps:
        - name: Check out code
          uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: python -m pip install -r requirements.txt
        - name: Lint with flake8
          run: |
            pip install flake8
            flake8 ./src --count --show-source --statistics
    
        - name: Install pytest
          run: python -m pip install pytest pytest-cov
        - name: Run tests
          run: pytest --cov=src ./test/
        - name: Perform security scan
          run: |
            pip install bandit
            bandit -r . -ll -ii -x ./test -x ./venv