name: PR tests

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v3
        - name: Set up Python 3.11
          uses: actions/setup-python@v2
          with:
            python-version: 3.11
        - name: Install dependencies
          run: python -m pip install -r requirements.txt
        - name: Install pytest
          run: python -m pip install pytest
        - name: Run tests
          run: pytest test
